### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by NikunjKhangwal** [zacharee/InstallWithOptions#15]
I tried this app in my friend's phone and for some weird reason the app keeps loading after selecting the apk, bypass low sdk and hitting install.
Device is Samsung S21 FE exynos & Android 14

**Comment by Lucifer7535** [comment]
I am also getting the same issue when trying to install a app.

**Comment by AngelMende3z** [comment]
I have also tried to install anything and I left it for 1 hour to install and it never got past the loading screen

**Comment by drogga** [comment]
...but does the target app get installed anyway or not ?, because for instance when I'm using SAI with custom flags/attributes/params in the super secret settings > custom install-create command, it always says that it's installing forever, but the apps get installed anyway, so it might be just a visual thing, which doesn't report or know when the installation is finished.

**Comment by NikunjKhangwal** [comment]
Nope, it doesn't install

**Comment by Gadgetonomy** [comment]
Same issue (Galaxy S24 Ultra)

**Comment by zacharee** [comment]
This should be fixed in 0.4.2
