### ISSUE TITLE
Problems with installing older apps

### ISSUE THREAD

**Issue by cjocollin** [zacharee/InstallWithOptions#22]
I keep getting this kind of error when trying to Bypass Low Target SDK Block on older apps:

com.dotgears.flappybird INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

I tried two different apps

On Pixel 7 Pro, on Android 15 Beta
![Screenshot_20240413-115018](https://github.com/zacharee/InstallWithOptions/assets/74850089/f217d7e4-92f9-4f44-a559-a591449c9992)

**Comment by drogga** [comment]
This has nothing to do with SDK, it tells you that the package doesn't contain the necessary libraries (ABIs) for your CPU, which only supports arm64-v8a, this app can't bypass that to install ones with armeabi-v7a. I've seen a Magisk module (root) that claims to be able to bypass this stupid restrictions, but the new CPUs just don't any longer support the instructions set. Your's is one of those that still does I think, but the restriction/limitation is placed by Google on a software level, rather than hardware like in Snapdragon 8 Gen 3 that no longer supports 32-bit.

**Comment by mkstskkv** [comment]
I have same problem with installing daydream apks on pixel 7, android 14.

![Screenshot_20240421-155423](https://github.com/zacharee/InstallWithOptions/assets/105938413/cb962cb2-2554-4017-adfb-169cfd149a81)

**Comment by drogga** [comment]
In that case and considering my comment above - I don't see a point in posting this, given that it's not this app's fault and that it can't do anything about this.
