### ISSUE TITLE
Signature error? 

### ISSUE THREAD

**Issue by HyperFire16** [zacharee/InstallWithOptions#24]
I do apologise in advance, but I'm not experts in this stuff. So it'd be much appreciated if anyone could explain what's wrong here.
![Screenshot_20240416-193019](https://github.com/zacharee/InstallWithOptions/assets/145864934/508a92f3-2f95-4955-b968-c0fb1adf98be)

**Comment by drogga** [comment]
@HyperFire16
It the package is not signed with Scheme v2 or at all. You can easily see the signature schemes with MT Manager and even resign with v1+v2+v3, but keep in mind that there might be a protection, so the app might crash because of this. There's no attribute/flag/param/command that can bypass this as far as I'm aware.
This is yet another limitation/restriction BS in modern android vers., along with the targetSdkVersion and architecture (app needing to have arm64-v8a natives, if it uses any).

**Comment by drogga** [comment]
BTW, is this something you've built (looking at the package name: com.open.source) ?

**Comment by drogga** [comment]
@HyperFire16
I believe you can close this now...
