### ISSUE TITLE
Can't downgrade app.

### ISSUE THREAD

**Issue by rejuanad99** [zacharee/InstallWithOptions#26]
As the title says I can't downgrade the even though I installed it with this app.
![Screenshot_20240501_212529_Install with Options](https://github.com/zacharee/InstallWithOptions/assets/49226370/0caab38d-c48e-41e1-a277-13921dac5dbe)
It throw this error.

**Comment by rejuanad99** [comment]
I'm using shizuku mode.

**Comment by drogga** [comment]
I just downgraded the exact same versions of the exact same app on A.8 with only 2 options: `Allow Downgrade` and `Replace Existing`, because I don't have the `Enable Rollback` on, which is dependent on the OS ver. I guess, my authorizer is Root, instead of Shizuku, but that shouldn't be the problem, are you sure you enabled the "Replace Existing" option, because it's a must and should be enabled by default IMO and it won't hurt even if you are not installing over an existing package.

**Comment by rejuanad99** [comment]
> I just downgraded the exact same versions of the exact same app on A.8 with only 2 options: `Allow Downgrade` and `Replace Existing`, because I don't have the `Enable Rollback` one, which is dependent on the OS ver. I guess, my authorizer is Root, instead of Shizuku, but that shouldn't be the problem, are you sure you enabled the "Replace Existing" option, because it's a must and should be enabled by default IMO and it won't hurt even if you are not installing over an existing package.

It doesn't work even with replace existing option selected.

**Comment by drogga** [comment]
Disable any other option than the 2 I mentioned, because I've tried with Shizuku and it installed an older build as well, you can also try with InstallerX or any other alternative, even manually, by using the -d & -r attributes/params/flags in the install command, just to see if they will work.

**Comment by rejuanad99** [comment]
Nope, doesn't work, it did worked with my rooted phone. Which also running android 14.

**Comment by drogga** [comment]
Must be the package installer, unfortunately I can't help in that case, but I'm interested in playing around, making it install, but since I don't have the device on hand - I can't, sorry, you can probably try to uninstall any updates of it/them, but the system one might have a patch for this, so this might not work as well, personally, I can also downgrade by installing with MT Manager, it usually takes care of such things if it has any of the 2 authorizers: Root or Shizuku, but make sure that Shizuku is active and the app is enabled inside.

**Comment by rejuanad99** [comment]
If I use replace existing will the data be deleted as well?

**Comment by zacharee** [comment]
No, it resumes the download.

**Comment by rejuanad99** [comment]
Thanks

**Comment by Russe098** [comment]
Please make the app so that it works in all versions of Android

**Comment by drogga** [comment]
Russ - In general [A.4.0 > 15] or just this option, because I don't think it's possible or makes sense for a number of reasons, one is the availability of the flags in lower OS vers., the other is Shizuku [7.0+ nowadays], but this is for another issue ticket... But If you mean the Downgrade option, then as I mentioned above - Google crippled it, so now [14+] it requires an attribute/param in the AndroidManifest.xml that indicates that the package is debuggable and I tested by installing the same exact ver. with the RollBack option and then tried to downgrade, which didn't work. I no longer have anything with A.14 to further play around with the downgrade, not that there seems to be a point, but I've tested with debuggable packages and it works as it should.
