### ISSUE TITLE
Install button disabled

### ISSUE THREAD

**Issue by itm1960** [zacharee/InstallWithOptions#46]
I'm trying the install Pure Calendar widget on an unrooted Galaxy S24 Ultra. I managed to get Shizuku started from my PC using ADB, and installed InstallWithOptions 0.6.1. I've selected the APK file and entered the package name (org.koxx.pure_calendar). Also selected "Bypass Low Target SDK Block. But the "Install" button is disabled. Any ideas?

**Comment by drogga** [comment]
Why are you using the installer spoofing options like this, to make the app think it installed itself ?, it's meant to be used only when necessary and nowadays apps are smarter than this and cannot be fooled that easy to think that PS is the installer, that option is for this, you don't have to use it, but if you want to, then try entering "com.android.vending", the install button is probably greyed out, either because that package doesn't exist or there's actually no file selected in the queue.
Also try to disable "Bypass Low Target SDK Block" and enable it back, because IWO gets confused and it fails to install sometime, or actually it work if you enable/disable any other option, it doesn't actually matter, it's odd tho.
