### ISSUE TITLE
Errors Installing Issue

### ISSUE THREAD

**Issue by KleoLavi85** [zacharee/InstallWithOptions#47]
The app cannot Bypass Low Target SDK Block for some low version build .apk files

[Screenshot_20240721_020356_Install with Options.png](https://github.com/user-attachments/assets/d98d1b16-31ee-4836-a93a-b3de74d1b07b)

**Comment by drogga** [comment]
If you've bothered to search ABIs with G. or any other search engine and read a little, you would've found that it's about CPU architecture and libraries and the error msg. means that your device doesn't support armeabi-v7a, but only arm64-v8a, which flappy bird doesn't have.

**Comment by Aspens2** [comment]
Why do you have do be such a bitch for no reason lmao

**Comment by Tectract** [comment]
Hey I'm getting this error trying to install an app, that was already installed on my phone. Somehow google play store "auto-updated". So I KNOW this app and APK works on this phone because it was previously installed with no issue.

Any other reason this "no matching ABIs" error could appear, or any way to bypass it???

**Comment by Tectract** [comment]
I think Android actually "updated" itself to remove old arm abi libs so I can't install those apps anymore without somehow rebuilding them!

**Comment by drogga** [comment]
ReBuilding them won't help, unless you find and add arm64-v8a libs for that particular app & ver. in the package, but then you might face either incompatibility due to lower targetSdkVersion (bypassable) it it's not just the ABIs issue or the app might have integrity checks.
What configuration you have - device, android ver., custom ROM, Root, etc. ?
