### ISSUE TITLE
Assuming remounting app isn't possible

### ISSUE THREAD

**Issue by PeterKW** [zacharee/InstallWithOptions#57]
I'm assuming this isn't possible but wanted to double check in case I'd misunderstood. 

I think to apply a patch to use Google Recorder requires a rooted device and can't be done another way e.g. using adb?

Thank you very much!

https://revanced.app/patches?pkg=com.google.android.apps.recorder

![Screenshot_20241007-160031.png](https://github.com/user-attachments/assets/5432fe5c-e73c-4c71-941d-236361f43143)

**Comment by PeterKW** [comment]
Sorry, couldn't see a way of putting this in the GitHub discussion category rather than an 'issue'

**Comment by zacharee** [comment]
"Mounting" makes me think it's referring to using a Magisk module to overlay the existing stock Recorder app, but I'm not really sure what it means. If it is saying that the stock app has to already be installed, then Install With Options can't install the patched version because of the signature mismatch.

**Comment by PeterKW** [comment]
That makes sense, thanks!
