### ISSUE TITLE
Add option to use no shizuku

### ISSUE THREAD

**Issue by HydroIgnite** [zacharee/InstallWithOptions#67]
Just asking but can you make an option to make the app not use shizuku to just install apps because it's kinda bad for me to enable shizuku everytime when I want to install an app. So maybe make a tab for settings and make a toggle to not use shizuku and remove any options to install that needs shizuku, I mean like if I don't wanna use shizuku then the options that need shizuku to work will be dimmed which means that it won't work but if I click on the option that needs shizuku, a popup will appear and say that it needs shizuku for it to work. So maybe a yes or a no? If you add it then this will be my main app installer ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by zacharee** [comment]
All of the options require Shizuku as implemented. The point of this app is to expose more advanced install flags without having to use ADB shell, not necessarily to be a general purpose APK installer; there are a lot of other options for that.

**Comment by drogga** [comment]
Well it's not a terrible idea, given that the system/package installer doesn't seem know what to do with bundles/splits archived in any of the popular file extensions they are distributed as, the best case is - it will open them as what they are - archives and they can't natively be installed (AFAIK), technically if Zacharee wanted IWO could be made to just and only do that - install bundles/splits and maybe setting an install location (internal/external) only on A.9 and below (as pointless as it might seem), other than that every other option can be disabled/hidden/greyed-out because they can't work without an authorizer, being Shizuku/Sui/Root. I use a file manager that can install bundles without any options or picking which split to install from a bundle archive, which is bad, but at least I have options like SAI or IWO if I have an authorizer (Shizuku/Root), plenty of session installers out there, but nothing that advanced as IWO (short of InstallWithOptions).

**Comment by HydroIgnite** [comment]
> Well it's not a terrible idea, given that the system/package installer or rather most file managers, especially the build-in/system ones don't seem know what to do with bundles/splits archived in any of the popular file extensions they are distributed as, the best case is - they will open them as what they are - archives and they can't natively be installed (AFAIK), technically if Zacharee wanted IWO could be made to just and only do that - install bundles/splits and maybe setting an install location (internal/external) only on A.9 and below (as pointless as it might seem), other than that every other option can be disabled/hidden/greyed-out because they can't work without an authorizer, being Shizuku/Root _(and maybe even Dhizuku - uses DeviceOwner - aka. elevated Device Admin with a command, which doesn't have to be executed after a reboot). I use a file manager that can install bundles without any options or picking which split to install from a bundle archive, which is bad, but at least I have options like SAI or IWO if I have an authorizer (Shizuku/Root), plenty of session installers out there, but nothing that advanced as IWO (short of InstallWithOptions)_.

I just like the UI and looks of it cuz I get bored of the old UI and when I keep seeing it everytime I install an app plus this app is more reliable for more tasks to not waste my time ya know what I mean ;)
